# Generated by Django 5.2.12 on 2026-03-22 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('avg_attention_score', models.FloatField(default=0.0)),
                ('avg_emotion_score', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20)),
                ('emotion_data', models.JSONField(blank=True, default=dict)),
                ('attention_data', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_sessions', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
